version: '3'

services:
  web:
    container_name: techlib_web
    build: ./web
    entrypoint:
      - sh
    command:
      - -c
      - |
        [ -f ~/.exec-once ] || {
          yarn install && touch ~/.exec-once
        }
        yarn start
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/web
    ports:
      - '3000:3000'
    tty: true

  api:
    build: ./api
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./api/src:/api/src/
    ports:
      - '8000:8000'
    tty: true
