version: '3'

services:
  db:
    container_name: techlib_db
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=admin
      - POSTGRES_DB=techlib_db

  api:
    container_name: techlib_api
    build:
      context: ./api
      target: develop
    command: /bin/sh -c "cargo watch -x run --poll"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - db

  web:
    container_name: techlib_web
    build: ./web
    entrypoint:
      - sh
    command:
      - -c
      - |
        [ -f ~/.exec-once ] || {
          yarn install && touch ~/.exec-once
        }
        yarn start
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/web
      - ./web/node_modules:/web/node_modules
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - api

  nginx:
    container_name: techlib_nginx
    image: nginx:1.22.0
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - web

volumes:
  db-store:
