version: '3'

services:
  web:
    container_name: techlib_web
    build: .docker/web/
    entrypoint:
      - sh
    command:
      - -c
      - |
        [ -f ~/.exec-once ] || {
          yarn install && touch ~/.exec-once
        }
        yarn start
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/web
    ports:
      - '3000:3000'
    tty: true
