version: '3'

services:
  web:
    container_name: techlib_web
    build: ./web
    entrypoint:
      - sh
    command:
      - -c
      - |
        [ -f ~/.exec-once ] || {
          yarn install && touch ~/.exec-once
        }
        yarn start
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/usr/web
    ports:
      - '3000:3000'
    tty: true

  api:
    build: ./api
    command: cargo watch -x run
    volumes:
      - ./api:/usr/api
    ports:
      - '8000:8000'
    tty: true
